FROM php:8.3

RUN apt-get update && apt-get install -y \
    libonig-dev \
    libxml2-dev \
    sqlite3 \
    libsqlite3-dev

RUN docker-php-ext-install pdo pdo_mysql mbstring xml

WORKDIR /var/www

COPY . /var/www

RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache

COPY .env /var/www/.env

RUN php artisan key:generate

RUN php artisan migrate --seed

EXPOSE 8000

CMD php artisan serve --host=0.0.0.0 --port=8000

